"""add_password_reset_fields

Revision ID: 801b03186c43
Revises: 99e0b3197e26
Create Date: 2026-02-18 15:03:28.451039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801b03186c43'
down_revision: Union[str, None] = '99e0b3197e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'reset_token_expires')
    op.drop_column('employees', 'reset_token')
    # ### end Alembic commands ###
